src/App/CoreBundle/Entity/PromoBlock.php
<?php

namespace App\CoreBundle\Entity;

use App\CoreBundle\Model\Choice\IconChoice;
use Doctrine\ORM\Mapping as ORM;
use Vivo\UtilBundle\Behaviour\Model\CsrfIntentionTrait;
use Vivo\UtilBundle\Behaviour\Model\TimestampableTrait;

/**
 * PromoBlock.
 *
 * @ORM\Table(name="app_core_promo_block")
 * @ORM\Entity(repositoryClass="App\CoreBundle\Repository\PromoBlockRepository")
 */
class PromoBlock
{
    use TimestampableTrait;
    use CsrfIntentionTrait;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="string", length=255, nullable=true)
     */
    protected $content;

    /**
     * @var int
     *
     * @ORM\Column(name="icon", type="smallint", nullable=true)
     */
    protected $icon;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=100, nullable=true)
     */
    protected $url;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $newWindow;

    /**
     * @var int
     *
     * @ORM\Column(name="icon_position", type="smallint", nullable=true)
     */
    protected $iconPosition;

    public function __construct()
    {
        $this->iconPosition = 1;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name.
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set content.
     *
     * @param string $content
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set icon.
     *
     * @param int $icon
     */
    public function setIcon($icon)
    {
        $this->icon = $icon;

        return $this;
    }

    /**
     * @return int
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Get icon label.
     *
     * @return string
     */
    public function getIconClass()
    {
        if (array_key_exists($this->icon, IconChoice::$icons)) {
            return IconChoice::$classes[$this->icon];
        }
    }

    /**
     * Set url.
     *
     * @param string $url
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set newWindow.
     *
     * @param bool $newWindow
     */
    public function setNewWindow($newWindow)
    {
        $this->newWindow = $newWindow;

        return $this;
    }

    /**
     * @return bool
     */
    public function getNewWindow()
    {
        return $this->newWindow;
    }

    /**
     * Set iconPosition.
     *
     * @param bool $iconPosition
     */
    public function setIconPosition($iconPosition)
    {
        $this->iconPosition = $iconPosition;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIconPosition()
    {
        return $this->iconPosition;
    }
}

src/App/CoreBundle/Form/Type/Admin/FruitType.php
<?php

namespace App\CoreBundle\Form\Type\Admin;

use App\CoreBundle\Model\Choice\ColorClassChoice;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class FruitType extends AbstractType
{
    /**
     * @var string
     */
    protected $fruitSlugClass;

    /**
     * @param string $fruitSlugClass
     */
    public function __construct($fruitSlugClass)
    {
        $this->fruitSlugClass = $fruitSlugClass;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $fruitSlugReflection = new \ReflectionClass($this->fruitSlugClass);

        $builder
            ->add('disabledAt', 'vivo_util_checkbox_datetime', array(
                'inverted' => true,
                'label' => 'Active',
                'required' => false,
                'help_inline' => 'Tick to enable fruit',
            ))
            ->add('name')
            ->add('subtitle')
            ->add('intro', 'textarea', array(
                'label' => 'Homepage Card Intro',
                'help_inline' => 'For homepage card - Max 255 characters',
            ))
            ->add('pageIntroduction', 'textarea', array(
                'label' => 'Page Introduction',
            ))
            ->add('content', 'ckeditor', array(
                'label' => 'Content',
                'help_inline' => '<p class="help-inline alert">1 column full width images upload at: 1220px wide (615px wide if a caption or sidebar is enabled). <br>2 column images upload at: 560x373px.<br>3 Podcast images only: 350x270px.</p>',
            ))
            ->add('colorClass', 'choice', array(
                'choices' => ColorClassChoice::$choices,
            ))
            ->add('primaryImage', 'vivo_asset_asset_image_collection', array(
                'label' => 'Main Card Image: 360x210px',
                'multiple' => false,
                'options' => array(
                    'data_class' => 'App\CoreBundle\Entity\FruitImage',
                ),
            ))
            ->add('contentImage', 'vivo_asset_asset_image_collection', array(
                'multiple' => false,
                'label' => 'Content Image: 1220x670px (without caption) or 910x500px (with caption)',
                'button_text' => 'Upload Image',
                'options' => array(
                    'data_class' => 'App\CoreBundle\Entity\FruitImage',
                ),
            ))
            ->add('bannerImage', 'vivo_asset_asset_image_collection', array(
                'label' => 'Banner Image',
                'multiple' => false,
                'options' => array(
                    'data_class' => 'App\CoreBundle\Entity\FruitImage',
                ),
            ))
            ->add('primarySlug', 'vivo_slug', array(
                'slug_entity' => $fruitSlugReflection->newInstance(),
                'label' => 'URL',
                'help_block' => 'eg /fruits/<strong>url</strong> The /fruits part is not required',
            ))
            ->add('promoGroup', 'entity', array(
                'required' => false,
                'empty_value' => 'None',
                'class' => 'AppCoreBundle:PromoBlockGroup',
                'property' => 'name',
                'label' => 'Promo Block',
                'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('b')
                            ->orderBy('b.name', 'ASC')
                            ->addOrderBy('b.id', 'ASC');
                    },
            ))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\CoreBundle\Entity\Fruit',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'app_corebundle_fruit';
    }
}

src/App/CoreBundle/Controller/Admin/FruitController.php
<?php

namespace App\CoreBundle\Controller\Admin;

use App\CoreBundle\Entity\Fruit;
use App\CoreBundle\Form\Type\Admin\FruitType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\InvalidCsrfTokenException;
use Vivo\UtilBundle\Form\Model\SearchList;

class FruitController extends Controller
{
    /**
     * Lists all fruit entities.
     */
    public function indexAction(Request $request)
    {
        $fruitRepository = $this->getDoctrine()->getManager()->getRepository('AppCoreBundle:Fruit');
        $paginator = $this->get('knp_paginator');

        $queryBuilder = $fruitRepository->createQueryBuilder('fruit')
            ->select('fruit')
            ->orderBy('fruit.updatedAt', 'desc');

        $searchList = new SearchList();
        $searchList->setEqualColumns(array('fruit.id'))
            ->setLikeColumns(array('fruit.name'));

        $form = $this->createForm('search_list', $searchList);
        $form->handleRequest($request);

        return $this->get('vivo_util.util.ajax_response')->getResponse(
            $request,
            '@AppCore/Admin/Fruit/index.html.twig',
            array(
                'searchForm' => $form->createView(),
                'pagination' => $paginator->paginate($searchList->getSearchQueryBuilder($queryBuilder), $request->query->get('page', 1), 50),
            )
        );
    }

    /**
     * Creates a new Fruit entity.
     */
    public function createAction(Request $request)
    {
        $fruit = new Fruit();

        $form = $this->createForm(new FruitType('App\CoreBundle\Entity\FruitSlug'), $fruit);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($fruit);
            $em->flush();
            $this->addFlash('success', 'admin.flash.fruit.create.success');

            return $this->redirect($this->generateUrl('app_core.admin.fruit.index'));
        }

        return $this->render('@AppCore/Admin/Fruit/create.html.twig', array(
            'fruit' => $fruit,
            'form' => $form->createView(),
        ));
    }

    /**
     * Updates a Fruit entity.
     */
    public function updateAction(Request $request, $id)
    {
        /** @var \App\CoreBundle\Repository\FruitRepository $fruitRepository */
        $fruitRepository = $this->getDoctrine()->getManager()->getRepository('AppCoreBundle:Fruit');
        $fruit = $fruitRepository->findOneById($id);

        if (!$fruit) {
            throw $this->createNotFoundException('Unable to find branch entity.');
        }

        if ($request->isMethod('POST')) {
        }

        $form = $this->createForm(new FruitType('App\CoreBundle\Entity\FruitSlug'), $fruit);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $em->persist($fruit);

            $em->flush();
            $this->addFlash('success', 'admin.flash.fruit.update.success');

            return $this->redirect($this->generateUrl('app_core.admin.fruit.index'));
        }

        return $this->render('@AppCore/Admin/Fruit/update.html.twig', array(
            'fruit' => $fruit,
            'form' => $form->createView(),
        ));
    }

    /**
     * Deletes a Store entity.
     */
    public function deleteAction($id, $token)
    {
        $fruitRepository = $this->getDoctrine()->getManager()->getRepository('AppCoreBundle:Fruit');
        $fruit = $fruitRepository->find($id);
        $csrf = $this->get('form.csrf_provider');

        if (!$fruitRepository) {
            throw $this->createNotFoundException('Unable to find branch entity.');
        }

        if (true !== $csrf->isCsrfTokenValid($fruit->getCsrfIntention('delete'), $token)) {
            throw new InvalidCsrfTokenException('Invalid csrf token.');
        } else {
            $em = $this->getDoctrine()->getManager();
            $em->remove($fruit);
            $em->flush();
            $this->addFlash('success', 'admin.flash.fruit.delete.success');
        }

        return $this->redirect($this->generateUrl('app_core.admin.fruit.index'));
    }

    /**
     * Add flash message.
     *
     * @param $type
     * @param $translationKey
     */
    protected function addFlash($type, $translationKey)
    {
        $value = $this->get('translator')->trans($translationKey, array(), 'AppCoreBundle');
        $this->get('session')->getFlashBag()->add($type, $value);
    }

    /**
     * Rank fruit entities.
     */
    public function rankAction(Request $request)
    {
        /** @var \App\CoreBundle\Repository\FruitRepository $fruitRepository */
        $fruitRepository = $this->getDoctrine()->getRepository('AppCoreBundle:Fruit');
        $fruits = $fruitRepository->findAll();

        if ($request->isMethod('POST')) {
            if (!$request->request->get('ranks')) {
                $this->addFlash('info', 'admin.flash.fruit.rank.none');
            } else {
                parse_str($request->request->get('ranks'), $ranks);

                if (!isset($ranks['app_core_fruit']) || !is_array($ranks['app_core_fruit']) || count($ranks['app_core_fruit']) !== count($fruits)) {
                    $this->addFlash('error', 'admin.flash.fruit.rank.invalid');
                } else {
                    $rank = 0;
                    foreach ($ranks['app_core_fruit'] as $fruitId => $parent) {
                        $fruitId = (int) $fruitId;

                        if ($fruitId) {
                            /** @var \App\CoreBundle\Entity\Fruit $fruit */
                            if ($fruit = $fruitRepository->find($fruitId)) {
                                $fruit->setRank(++$rank);
                            }
                        }
                    }

                    if ($rank > 0) {
                        $em = $this->getDoctrine()->getManager();
                        $em->flush();
                        $this->addFlash('success', 'admin.flash.fruit.rank.success');
                    } else {
                        $this->addFlash('success', 'admin.flash.fruit.rank.none');
                    }
                }
            }

            return $this->redirect($this->generateUrl('app_core.admin.fruit.rank'));
        }

        return $this->render('@AppCore/Admin/Fruit/rank.html.twig', array(
            'fruits' => $fruits,
        ));
    }
}

src/App/CoreBundle/Controller/FruitController.php
<?php

namespace App\CoreBundle\Controller;

use App\CoreBundle\Entity\Fruit;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Vivo\PageBundle\Event\Events;
use Vivo\PageBundle\Event\PrepareSeoEvent;
use Vivo\PageBundle\Model\Page;
use Vivo\PageBundle\Model\PageInterface;
use App\CoreBundle\Repository\FruitRepository;

class FruitController extends Controller
{
    public function indexAction(Request $request, PageInterface $cmsPage)
    {
        $response = new Response();
        $response->setSharedMaxAge(10); // Number of seconds to check headers for last modified date

        if ($response->isNotModified($request)) {
            return $response;
        }

        /** @var FruitRepository $fruitRepo */
        $fruitRepo = $this->get('app_core.repository.fruit');

        $fruits = $fruitRepo->findAllForListPage();

        /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $eventDispatcher */
        $eventDispatcher = $this->container->get('event_dispatcher');
        $eventDispatcher->dispatch(Events::PREPARE_SEO, new PrepareSeoEvent($cmsPage, $request));

        return $this->render('@AppCore/Fruit/index.html.twig', array(
            'page' => $cmsPage,
            'fruits' => $fruits,
        ), $response);
    }

    public function viewAction(Request $request, $slug, PageInterface $cmsPage)
    {
        /** @var FruitRepository $fruitRepo */
        $fruitRepo = $this->get('app_core.repository.fruit');

        /** @var Fruit $fruit */
        $fruit = $fruitRepo->findOneBySlugWithMenuNodes($slug);

        if (!$fruit) {
            return $this->redirect($this->generateUrl('app_core.fruit.index'), 301);
        }

        /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $eventDispatcher */
        $eventDispatcher = $this->container->get('event_dispatcher');
        $eventDispatcher->dispatch(Events::PREPARE_SEO, new PrepareSeoEvent($cmsPage, $request));

        $seoPage = $this->get('vivo_site.seo.page');

        $seoPage->addTitlePart($fruit->getName());

        return $this->render('@AppCore/Fruit/view.html.twig', array(
            'page' => $cmsPage,
            'fruit' => $fruit,
        ));
    }

    public function homepageCardsAction(Request $request)
    {
        $response = new Response();
        $response->setSharedMaxAge(10); // Number of seconds to check headers for last modified date

        if ($response->isNotModified($request)) {
            return $response;
        }

        /** @var FruitRepository $fruitRepo */
        $fruitRepo = $this->get('app_core.repository.fruit');

        $fruits = $fruitRepo->findAllForListPage();

        return $this->render('@AppCore/Fruit/cards.html.twig', array(
            'fruits' => $fruits,
        ), $response);
    }
}

src/App/CoreBundle/Resources/views/Fruit/_menu_item.html.twig
<a{% for attrname, attrvalue in item.linkAttributes %} {{ attrname }}="{{ attrvalue }}"{% endfor %} data-url="{{ url('app_core.fruit.view',{slug: fruit.primarySlug.slug }) }}">{{ fruit.name }}</a>

src/App/CoreBundle/Resources/views/Fruit/cards.html.twig
<div class="block tertiary-alt-colour tear-top">
    <div class="wrapper">

        <div class="fruit-cards">
            <ul>
                {% for fruit in fruits %}
                    {% set firstimg = fruit.primaryImage %}
                    <li class="{{ fruit.colorClass }}">
                        <a href="{{ fruit.primarySlug is not null and fruit.primarySlug.slug is not null ? path('app_core.fruit.view', { slug: fruit.primarySlug.slug }) : 'javascript:void(0)' }}" title="{{ fruit.name }}">
                            <div class="card-pop">
                                <div class="image" style="background-image: url('{{ firstimg.imagePreviewPath|imagine_filter("360x210p") }}');"></div>
                                <div class="text">
                                    {% include 'Elements/common/tear_top_small.html.twig' %}

                                    <div class="hidden">
                                        <span class="subtitle">{{ fruit.subtitle }}</span>
                                        <h3>{{ fruit.name }}</h3>
                                    </div>
                                    <p>{{ fruit.intro }}</p>
                                    {% include 'Elements/common/tear_bottom_small.html.twig' %}
                                </div>
                            </div>
                            <div class="card-inner">
                                <div class="icon">
                                    <i class="pin-{{ fruit.colorClass }}-circled"></i>
                                </div>
                                <span class="subtitle">{{ fruit.subtitle }}</span>
                                <h3>{{ fruit.name }}</h3>
                            </div>
                        </a>
                    </li>

                {% endfor %}
            </ul>
        </div>


    </div>
</div>

src/App/CoreBundle/Resources/views/Fruit/index.html.twig
{% extends '@VivoPage/Page/view.html.twig' %}

{% block body_class %}fruits{% endblock body_class %}

{% block post_title_block %}
    {% if page.assetGroupByAlias('banner') is not empty and page.assetGroupByAlias('banner').assets is not empty %}
        {% for asset in page.assetGroupByAlias('banner').assets %}
            <div class="hero-image" style="background-image:url('{{ asset.imagePreviewPath|imagine_filter('1920x450p') }}');"></div>
        {% endfor %}
    {% endif %}
{% endblock post_title_block %}

{% block post_main_content_block %}
    <div class="block tertiary-colour cards tear-top">
        <div class="wrapper">

            <div class="fruit-cards">
                <ul>
                    {% for fruit in fruits %}
                        {% set firstimg = fruit.primaryImage %}
                        <li class="{{ fruit.colorClass }}">
                            <div class="card-pop">
                                <div class="image" style="background-image: url('{{ firstimg.imagePreviewPath|imagine_filter("360x210p") }}');"></div>
                                <div class="text">
                                    {% include 'Elements/common/tear_top_small.html.twig' %}

                                    <div class="hidden">
                                        <span class="subtitle">{{ fruit.subtitle }}</span>
                                        <h3>{{ fruit.name }}</h3>
                                    </div>
                                    <p>{{ fruit.intro }}</p>
                                    {% include 'Elements/common/tear_bottom_small.html.twig' %}
                                </div>
                            </div>
                            <div class="card-inner">
                                <div class="icon">
                                    <i class="pin-{{ fruit.colorClass }}-circled"></i>
                                </div>
                                <span class="subtitle">{{ fruit.subtitle }}</span>
                                <h3>
                                    <a href="{{ fruit.primarySlug is not null and fruit.primarySlug.slug is not null ? path('app_core.fruit.view', { slug: fruit.primarySlug.slug }) : 'javascript:void(0)' }}" title="{{ fruit.name }}">
                                        {{ fruit.name }}
                                    </a>
                                </h3>
                            </div>
                        </li>

                    {% endfor %}
                </ul>
            </div>


        </div>
    </div>
{% endblock post_main_content_block %}

{% block main_col_content %}
     {{ page.contentByAlias('main').content|default('')|raw }}
{% endblock main_col_content %}

src/App/CoreBundle/Resources/views/Fruit/view.html.twig
{% extends '@VivoPage/Page/view.html.twig' %}

{% block body_class %}{{ fruit.colorClass }}{% endblock body_class %}

{% block page_title %}
    {% if app.request.attributes.get('_route') == 'app_core.fruit.view' %}
        {{ fruit.name }}
    {% else %}
        {{ page.pageTitle }}
    {% endif %}
{% endblock page_title %}

{% block post_title_block %}
    {% if fruit.bannerImage is not empty and fruit.bannerImage is not empty %}
        <div class="hero-image" style="background-image:url('{{ fruit.bannerImage.imagePreviewPath|imagine_filter('1920x450p') }}');"></div>
    {% endif %}
{% endblock post_title_block %}


{% block main_intro_content %}
    {% if fruit.pageIntroduction is defined and fruit.pageIntroduction is not null %}
        <p class="intro">{{ fruit.pageIntroduction }}</p>
    {% endif %}
{% endblock main_intro_content %}

{% block main_intro_image %}
    {% if fruit.contentImage %}
        {% set image = fruit.contentImage %}
        <figure class="image-box {% if image.title is not null %}has-caption{% endif %}">
            <div class="image">
                <img src="{% if image.title is not null %}{{ image.imagePreviewPath|imagine_filter('920x505p') }}{% else %}{{ image.imagePreviewPath|imagine_filter('1220x670p') }}{% endif %}" alt="{{ image.alt }}" />
            </div>
            {% if image.title is not null %}
                <figcaption>{{ image.title }}</figcaption>
            {% endif %}
        </figure>
    {% endif %}
{% endblock main_intro_image %}

{% block main_col_content %}
    {{ fruit.content|default('')|raw }}
{% endblock main_col_content %}

{% block sidebar %}
    {% if fruit.promoGroup is defined and fruit.promoGroup is not null %}
        <div class="sidebar-promos">
            {% for promo in fruit.promoGroup.blocks %}
                <div class="promo">
                    <a {% if promo.block.newWindow %}target="_blank"{% endif %} href="{{ promo.block.url }}">
                        {% include 'Elements/common/tear_top_small.html.twig' %}

                        {% if promo.block.icon is not null and promo.block.iconPosition == 1%}<i class="{{ promo.block.iconClass }}"></i>{% endif %}
                        <span>{{ promo.block.content|nl2br|raw }}</span>
                        {% if promo.block.icon is not null and promo.block.iconPosition == 2%}<i class="{{ promo.block.iconClass }}"></i>{% endif %}

                        {% include 'Elements/common/tear_bottom_small.html.twig' %}

                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock sidebar %}